<!-- DA SISTEMARE IN BOOTSTRAP-->


<div if="faq">
<h3>Q: How can I order?</h3>
<p>You can order easily using our online platform. When you find a product you need, you can add it to cart, login and go through the ordering process. After the order is ready, you will receive order summary to your email. Order summary will also be stored to your account.
<br><br>
You can also easily make reorders afterwards by clicking the “reorder” button on any of your previously made orders. After clicking the “reorder” button the cart will open and you can change quantities or products.</p>
<h3>Q: I received an error message while placing my order, what can I do?</h3>
<p>Our customer care is always at your disposal to help you with the purchase procedure. If you encounter a problem you can call us, chat with us, or send us a message by attaching a screenshot of the page where the error occurred. Alternatively you can write to customer.service@yamamay.com
</p>
<h3>Q: How can I view the status of my order?</h3>
<p>You can view the information of your orders (in progress and past), by logging into your account, in the "My orders" section. If you have not registered on yamamay.com, you will find all the information in the order confirmation email.
</p>
<h3>Q: Is there a limit to the amount of products I can purchase?</h3>
<p>There are generally no limits regarding quantity or amount. However, Yamamay may reserve the right to limit the purchase of some particular limited series products.
</p>
<h3>Q: Can I change an order?</h3>
<p>You can change the order until the payment is confirmed. Once payment is received, it is no longer possible to change the order. This includes changing the size or color, removing or adding items, changing the billing address and the payment method.
</p>
</div>