<h2>Salve, controlla il log</h2>

<div data-bind="scope: 'its'">
<!-- ko template: getTemplate() --><!-- /ko -->

</div>

<script type="text/x-magento-init">
{
    "*":{
        "Magento_Ui/js/core/app": {
            "components" : {
                "its": {
                    "component": "Mrt_Modutest/js/view/its",
                    "template": "Mrt_Modutest/itsTemplate"
                    "tasks": [
                        {"nome": "Geronimo"},
                        {"cognome": "Pepperino"},
                        {"email": "io@chilosa.com"}
                        ]
                }
            }
        }
    }
}
</script>