<?php
$data = $block->getData('tickets');
?>

<h1>Tickets belli</h1>

<table id="ticket-table" class="table table-striped">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Message</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <?php
            foreach ($data as $ticket) {
                call_user_func_array('createRow', $ticket);
            }
            ?>
        </tr>
    </tbody>
</table>

<?php

function createRow($fName, $lName, $email, $message = "")
{
    print '<tr>' . PHP_EOL;
    // print '<td>' . $id . '</td>' . PHP_EOL;
    print '<td>' . $fName . '</td>' . PHP_EOL;
    print '<td>' . $lName . '</td>' . PHP_EOL;
    print '<td>' . $email . '</td>' . PHP_EOL;
    print '<td>' . $message . '</td>' . PHP_EOL;
    print '</tr>';
}

?>

<!--
<li repeat="foreach: tasks, item: 'task'">
<span translate="task().label"></span>
</li>
-->