<div data-bind="scope: 'componente1'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "*":{
        "Magento_Ui/js/core/app": {
            "components" : {
                "componente1": {
                    "component": "Test_PrimoModulo/js/view/componente1",
                    "template": "Test_PrimoModulo/componente1",
                    "tasks": [
                        { "id": 1, "label": "Task 4" },
                        { "id": 2, "label": "Task 5" },
                        { "id": 3, "label": "Task 6" },
                        { "id": 4, "label": "Task 7" }
                    ]
                }
            }
        }
    }
}
</script>
