<?php $data = $block->getData("my_key");
echo $data;
exit;
?>
<div>
    <table class="tabella-ticket">
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>email</th>
            <th>id</th>
            <th>testo</th>
        </tr>        
    </table>
    <button>
        <a href="http://109.74.193.11/primomodulo/page/tabella">Link</a>
    </button>
</div>