<?php
$data = $block->getData('tickets');
?>

<h1>Tickets (questo funzia, link a parte)</h1>

<table id="ticket-table" class="table table-striped">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Email</th>
            <th>Link</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <?php
            foreach ($data as $ticket) {
                call_user_func_array('createRow', $ticket);
            }
            ?>
        </tr>
    </tbody>
</table>

<?php

function createRow($fName, $lName, $email, $message = "")
{
    print '<tr>' . PHP_EOL;
    // print '<td>' . $id . '</td>' . PHP_EOL;
    print '<td>' . $fName . '</td>' . PHP_EOL;
    print '<td>' . $lName . '</td>' . PHP_EOL;
    print '<td>' . $email . '</td>' . PHP_EOL;
    print '<td>' . $message . '</td>' . PHP_EOL;
    print '</tr>';
}

?>


